// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensor.proto

package com.google.android.lib.mytracks.content;

public final class Sensor {
  private Sensor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.google.android.lib.mytracks.content.SensorState}
   *
   * <pre>
   * An enumeration of the state of a single sensor.
   * </pre>
   */
  public enum SensorState
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>NONE = 1;</code>
     *
     * <pre>
     * There is no sensor.
     * </pre>
     */
    NONE(0, 1),
    /**
     * <code>CONNECTING = 2;</code>
     *
     * <pre>
     * Now initiating an outgoing connection.
     * </pre>
     */
    CONNECTING(1, 2),
    /**
     * <code>CONNECTED = 3;</code>
     *
     * <pre>
     * Now connected to a remote device.
     * </pre>
     */
    CONNECTED(2, 3),
    /**
     * <code>DISCONNECTED = 4;</code>
     *
     * <pre>
     * A state where the sensor is not connected.
     * </pre>
     */
    DISCONNECTED(3, 4),
    /**
     * <code>SENDING = 5;</code>
     *
     * <pre>
     * This is the only state where the sensor data can be used.
     * </pre>
     */
    SENDING(4, 5),
    ;

    /**
     * <code>NONE = 1;</code>
     *
     * <pre>
     * There is no sensor.
     * </pre>
     */
    public static final int NONE_VALUE = 1;
    /**
     * <code>CONNECTING = 2;</code>
     *
     * <pre>
     * Now initiating an outgoing connection.
     * </pre>
     */
    public static final int CONNECTING_VALUE = 2;
    /**
     * <code>CONNECTED = 3;</code>
     *
     * <pre>
     * Now connected to a remote device.
     * </pre>
     */
    public static final int CONNECTED_VALUE = 3;
    /**
     * <code>DISCONNECTED = 4;</code>
     *
     * <pre>
     * A state where the sensor is not connected.
     * </pre>
     */
    public static final int DISCONNECTED_VALUE = 4;
    /**
     * <code>SENDING = 5;</code>
     *
     * <pre>
     * This is the only state where the sensor data can be used.
     * </pre>
     */
    public static final int SENDING_VALUE = 5;


    public final int getNumber() { return value; }

    public static SensorState valueOf(int value) {
      switch (value) {
        case 1: return NONE;
        case 2: return CONNECTING;
        case 3: return CONNECTED;
        case 4: return DISCONNECTED;
        case 5: return SENDING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SensorState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SensorState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SensorState>() {
            public SensorState findValueByNumber(int number) {
              return SensorState.valueOf(number);
            }
          };

    private final int value;

    private SensorState(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.google.android.lib.mytracks.content.SensorState)
  }

  public interface SensorDataOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];
    /**
     * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
     */
    boolean hasState();
    /**
     * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorState getState();

    // optional int32 value = 2;
    /**
     * <code>optional int32 value = 2;</code>
     *
     * <pre>
     * Value is only defined if state = SENDING.
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>optional int32 value = 2;</code>
     *
     * <pre>
     * Value is only defined if state = SENDING.
     * </pre>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code com.google.android.lib.mytracks.content.SensorData}
   *
   * <pre>
   * The state and possible reading for one integer sensor.
   * </pre>
   */
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessageLite
      implements SensorDataOrBuilder {
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SensorData(boolean noInit) {}

    private static final SensorData defaultInstance;
    public static SensorData getDefaultInstance() {
      return defaultInstance;
    }

    public SensorData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SensorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.google.android.lib.mytracks.content.Sensor.SensorState value = com.google.android.lib.mytracks.content.Sensor.SensorState.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                state_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SensorData> PARSER =
        new com.google.protobuf.AbstractParser<SensorData>() {
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];
    public static final int STATE_FIELD_NUMBER = 1;
    private com.google.android.lib.mytracks.content.Sensor.SensorState state_;
    /**
     * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorState getState() {
      return state_;
    }

    // optional int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>optional int32 value = 2;</code>
     *
     * <pre>
     * Value is only defined if state = SENDING.
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 value = 2;</code>
     *
     * <pre>
     * Value is only defined if state = SENDING.
     * </pre>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      state_ = com.google.android.lib.mytracks.content.Sensor.SensorState.NONE;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.lib.mytracks.content.Sensor.SensorData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.android.lib.mytracks.content.SensorData}
     *
     * <pre>
     * The state and possible reading for one integer sensor.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.lib.mytracks.content.Sensor.SensorData, Builder>
        implements com.google.android.lib.mytracks.content.Sensor.SensorDataOrBuilder {
      // Construct using com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        state_ = com.google.android.lib.mytracks.content.Sensor.SensorState.NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorData getDefaultInstanceForType() {
        return com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorData build() {
        com.google.android.lib.mytracks.content.Sensor.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorData buildPartial() {
        com.google.android.lib.mytracks.content.Sensor.SensorData result = new com.google.android.lib.mytracks.content.Sensor.SensorData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.android.lib.mytracks.content.Sensor.SensorData other) {
        if (other == com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.android.lib.mytracks.content.Sensor.SensorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.android.lib.mytracks.content.Sensor.SensorData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];
      private com.google.android.lib.mytracks.content.Sensor.SensorState state_ = com.google.android.lib.mytracks.content.Sensor.SensorState.NONE;
      /**
       * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorState getState() {
        return state_;
      }
      /**
       * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
       */
      public Builder setState(com.google.android.lib.mytracks.content.Sensor.SensorState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value;
        
        return this;
      }
      /**
       * <code>required .com.google.android.lib.mytracks.content.SensorState state = 1 [default = NONE];</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = com.google.android.lib.mytracks.content.Sensor.SensorState.NONE;
        
        return this;
      }

      // optional int32 value = 2;
      private int value_ ;
      /**
       * <code>optional int32 value = 2;</code>
       *
       * <pre>
       * Value is only defined if state = SENDING.
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 value = 2;</code>
       *
       * <pre>
       * Value is only defined if state = SENDING.
       * </pre>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 2;</code>
       *
       * <pre>
       * Value is only defined if state = SENDING.
       * </pre>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 value = 2;</code>
       *
       * <pre>
       * Value is only defined if state = SENDING.
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.android.lib.mytracks.content.SensorData)
    }

    static {
      defaultInstance = new SensorData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.android.lib.mytracks.content.SensorData)
  }

  public interface SensorDataSetOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional uint64 creation_time = 1 [default = 0];
    /**
     * <code>optional uint64 creation_time = 1 [default = 0];</code>
     *
     * <pre>
     * This is a required field.
     * </pre>
     */
    boolean hasCreationTime();
    /**
     * <code>optional uint64 creation_time = 1 [default = 0];</code>
     *
     * <pre>
     * This is a required field.
     * </pre>
     */
    long getCreationTime();

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
     */
    boolean hasHeartRate();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRate();

    // optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
     */
    boolean hasCadence();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getCadence();

    // optional .com.google.android.lib.mytracks.content.SensorData power = 4;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
     */
    boolean hasPower();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getPower();

    // optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
     */
    boolean hasBatteryLevel();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getBatteryLevel();

    // optional .com.google.android.lib.mytracks.content.SensorData attention = 6;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
     */
    boolean hasAttention();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getAttention();

    // optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
     */
    boolean hasMeditation();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getMeditation();

    // optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
     */
    boolean hasBpm();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getBpm();

    // optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
     */
    boolean hasRmssd();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getRmssd();

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
     */
    boolean hasHeartRateRc1();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc1();

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
     */
    boolean hasHeartRateRc2();
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
     */
    com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc2();
  }
  /**
   * Protobuf type {@code com.google.android.lib.mytracks.content.SensorDataSet}
   *
   * <pre>
   * A message to encapsulate sensor readings associated with a track point.
   * </pre>
   */
  public static final class SensorDataSet extends
      com.google.protobuf.GeneratedMessageLite
      implements SensorDataSetOrBuilder {
    // Use SensorDataSet.newBuilder() to construct.
    private SensorDataSet(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SensorDataSet(boolean noInit) {}

    private static final SensorDataSet defaultInstance;
    public static SensorDataSet getDefaultInstance() {
      return defaultInstance;
    }

    public SensorDataSet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SensorDataSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              creationTime_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = heartRate_.toBuilder();
              }
              heartRate_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartRate_);
                heartRate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = cadence_.toBuilder();
              }
              cadence_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cadence_);
                cadence_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = power_.toBuilder();
              }
              power_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(power_);
                power_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = batteryLevel_.toBuilder();
              }
              batteryLevel_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(batteryLevel_);
                batteryLevel_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = attention_.toBuilder();
              }
              attention_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(attention_);
                attention_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = meditation_.toBuilder();
              }
              meditation_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meditation_);
                meditation_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = bpm_.toBuilder();
              }
              bpm_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bpm_);
                bpm_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 74: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = rmssd_.toBuilder();
              }
              rmssd_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rmssd_);
                rmssd_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
            case 82: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000200) == 0x00000200)) {
                subBuilder = heartRateRc1_.toBuilder();
              }
              heartRateRc1_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartRateRc1_);
                heartRateRc1_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000200;
              break;
            }
            case 90: {
              com.google.android.lib.mytracks.content.Sensor.SensorData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000400) == 0x00000400)) {
                subBuilder = heartRateRc2_.toBuilder();
              }
              heartRateRc2_ = input.readMessage(com.google.android.lib.mytracks.content.Sensor.SensorData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartRateRc2_);
                heartRateRc2_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000400;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SensorDataSet> PARSER =
        new com.google.protobuf.AbstractParser<SensorDataSet>() {
      public SensorDataSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorDataSet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SensorDataSet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 creation_time = 1 [default = 0];
    public static final int CREATION_TIME_FIELD_NUMBER = 1;
    private long creationTime_;
    /**
     * <code>optional uint64 creation_time = 1 [default = 0];</code>
     *
     * <pre>
     * This is a required field.
     * </pre>
     */
    public boolean hasCreationTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 creation_time = 1 [default = 0];</code>
     *
     * <pre>
     * This is a required field.
     * </pre>
     */
    public long getCreationTime() {
      return creationTime_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;
    public static final int HEART_RATE_FIELD_NUMBER = 2;
    private com.google.android.lib.mytracks.content.Sensor.SensorData heartRate_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
     */
    public boolean hasHeartRate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRate() {
      return heartRate_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;
    public static final int CADENCE_FIELD_NUMBER = 3;
    private com.google.android.lib.mytracks.content.Sensor.SensorData cadence_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
     */
    public boolean hasCadence() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getCadence() {
      return cadence_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData power = 4;
    public static final int POWER_FIELD_NUMBER = 4;
    private com.google.android.lib.mytracks.content.Sensor.SensorData power_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
     */
    public boolean hasPower() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getPower() {
      return power_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;
    public static final int BATTERY_LEVEL_FIELD_NUMBER = 5;
    private com.google.android.lib.mytracks.content.Sensor.SensorData batteryLevel_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
     */
    public boolean hasBatteryLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getBatteryLevel() {
      return batteryLevel_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData attention = 6;
    public static final int ATTENTION_FIELD_NUMBER = 6;
    private com.google.android.lib.mytracks.content.Sensor.SensorData attention_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
     */
    public boolean hasAttention() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getAttention() {
      return attention_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;
    public static final int MEDITATION_FIELD_NUMBER = 7;
    private com.google.android.lib.mytracks.content.Sensor.SensorData meditation_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
     */
    public boolean hasMeditation() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getMeditation() {
      return meditation_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;
    public static final int BPM_FIELD_NUMBER = 8;
    private com.google.android.lib.mytracks.content.Sensor.SensorData bpm_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
     */
    public boolean hasBpm() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getBpm() {
      return bpm_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;
    public static final int RMSSD_FIELD_NUMBER = 9;
    private com.google.android.lib.mytracks.content.Sensor.SensorData rmssd_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
     */
    public boolean hasRmssd() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getRmssd() {
      return rmssd_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;
    public static final int HEART_RATE_RC1_FIELD_NUMBER = 10;
    private com.google.android.lib.mytracks.content.Sensor.SensorData heartRateRc1_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
     */
    public boolean hasHeartRateRc1() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc1() {
      return heartRateRc1_;
    }

    // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;
    public static final int HEART_RATE_RC2_FIELD_NUMBER = 11;
    private com.google.android.lib.mytracks.content.Sensor.SensorData heartRateRc2_;
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
     */
    public boolean hasHeartRateRc2() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
     */
    public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc2() {
      return heartRateRc2_;
    }

    private void initFields() {
      creationTime_ = 0L;
      heartRate_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      cadence_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      power_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      batteryLevel_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      attention_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      meditation_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      bpm_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      rmssd_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      heartRateRc1_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      heartRateRc2_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasHeartRate()) {
        if (!getHeartRate().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCadence()) {
        if (!getCadence().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPower()) {
        if (!getPower().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBatteryLevel()) {
        if (!getBatteryLevel().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAttention()) {
        if (!getAttention().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMeditation()) {
        if (!getMeditation().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBpm()) {
        if (!getBpm().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRmssd()) {
        if (!getRmssd().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartRateRc1()) {
        if (!getHeartRateRc1().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartRateRc2()) {
        if (!getHeartRateRc2().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, creationTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, heartRate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, cadence_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, power_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, batteryLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, attention_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, meditation_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, bpm_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, rmssd_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, heartRateRc1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(11, heartRateRc2_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, creationTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, heartRate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, cadence_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, power_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, batteryLevel_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, attention_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, meditation_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, bpm_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, rmssd_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, heartRateRc1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, heartRateRc2_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.lib.mytracks.content.Sensor.SensorDataSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.lib.mytracks.content.Sensor.SensorDataSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.google.android.lib.mytracks.content.SensorDataSet}
     *
     * <pre>
     * A message to encapsulate sensor readings associated with a track point.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.android.lib.mytracks.content.Sensor.SensorDataSet, Builder>
        implements com.google.android.lib.mytracks.content.Sensor.SensorDataSetOrBuilder {
      // Construct using com.google.android.lib.mytracks.content.Sensor.SensorDataSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        creationTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        heartRate_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        cadence_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000004);
        power_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000008);
        batteryLevel_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000010);
        attention_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000020);
        meditation_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000040);
        bpm_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000080);
        rmssd_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000100);
        heartRateRc1_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000200);
        heartRateRc2_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorDataSet getDefaultInstanceForType() {
        return com.google.android.lib.mytracks.content.Sensor.SensorDataSet.getDefaultInstance();
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorDataSet build() {
        com.google.android.lib.mytracks.content.Sensor.SensorDataSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.android.lib.mytracks.content.Sensor.SensorDataSet buildPartial() {
        com.google.android.lib.mytracks.content.Sensor.SensorDataSet result = new com.google.android.lib.mytracks.content.Sensor.SensorDataSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.creationTime_ = creationTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.heartRate_ = heartRate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cadence_ = cadence_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.power_ = power_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.batteryLevel_ = batteryLevel_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.attention_ = attention_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.meditation_ = meditation_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.bpm_ = bpm_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.rmssd_ = rmssd_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.heartRateRc1_ = heartRateRc1_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.heartRateRc2_ = heartRateRc2_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.google.android.lib.mytracks.content.Sensor.SensorDataSet other) {
        if (other == com.google.android.lib.mytracks.content.Sensor.SensorDataSet.getDefaultInstance()) return this;
        if (other.hasCreationTime()) {
          setCreationTime(other.getCreationTime());
        }
        if (other.hasHeartRate()) {
          mergeHeartRate(other.getHeartRate());
        }
        if (other.hasCadence()) {
          mergeCadence(other.getCadence());
        }
        if (other.hasPower()) {
          mergePower(other.getPower());
        }
        if (other.hasBatteryLevel()) {
          mergeBatteryLevel(other.getBatteryLevel());
        }
        if (other.hasAttention()) {
          mergeAttention(other.getAttention());
        }
        if (other.hasMeditation()) {
          mergeMeditation(other.getMeditation());
        }
        if (other.hasBpm()) {
          mergeBpm(other.getBpm());
        }
        if (other.hasRmssd()) {
          mergeRmssd(other.getRmssd());
        }
        if (other.hasHeartRateRc1()) {
          mergeHeartRateRc1(other.getHeartRateRc1());
        }
        if (other.hasHeartRateRc2()) {
          mergeHeartRateRc2(other.getHeartRateRc2());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (hasHeartRate()) {
          if (!getHeartRate().isInitialized()) {
            
            return false;
          }
        }
        if (hasCadence()) {
          if (!getCadence().isInitialized()) {
            
            return false;
          }
        }
        if (hasPower()) {
          if (!getPower().isInitialized()) {
            
            return false;
          }
        }
        if (hasBatteryLevel()) {
          if (!getBatteryLevel().isInitialized()) {
            
            return false;
          }
        }
        if (hasAttention()) {
          if (!getAttention().isInitialized()) {
            
            return false;
          }
        }
        if (hasMeditation()) {
          if (!getMeditation().isInitialized()) {
            
            return false;
          }
        }
        if (hasBpm()) {
          if (!getBpm().isInitialized()) {
            
            return false;
          }
        }
        if (hasRmssd()) {
          if (!getRmssd().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartRateRc1()) {
          if (!getHeartRateRc1().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartRateRc2()) {
          if (!getHeartRateRc2().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.android.lib.mytracks.content.Sensor.SensorDataSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.android.lib.mytracks.content.Sensor.SensorDataSet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 creation_time = 1 [default = 0];
      private long creationTime_ ;
      /**
       * <code>optional uint64 creation_time = 1 [default = 0];</code>
       *
       * <pre>
       * This is a required field.
       * </pre>
       */
      public boolean hasCreationTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 creation_time = 1 [default = 0];</code>
       *
       * <pre>
       * This is a required field.
       * </pre>
       */
      public long getCreationTime() {
        return creationTime_;
      }
      /**
       * <code>optional uint64 creation_time = 1 [default = 0];</code>
       *
       * <pre>
       * This is a required field.
       * </pre>
       */
      public Builder setCreationTime(long value) {
        bitField0_ |= 0x00000001;
        creationTime_ = value;
        
        return this;
      }
      /**
       * <code>optional uint64 creation_time = 1 [default = 0];</code>
       *
       * <pre>
       * This is a required field.
       * </pre>
       */
      public Builder clearCreationTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        creationTime_ = 0L;
        
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;
      private com.google.android.lib.mytracks.content.Sensor.SensorData heartRate_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public boolean hasHeartRate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRate() {
        return heartRate_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public Builder setHeartRate(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartRate_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public Builder setHeartRate(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        heartRate_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public Builder mergeHeartRate(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            heartRate_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          heartRate_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(heartRate_).mergeFrom(value).buildPartial();
        } else {
          heartRate_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate = 2;</code>
       */
      public Builder clearHeartRate() {
        heartRate_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;
      private com.google.android.lib.mytracks.content.Sensor.SensorData cadence_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public boolean hasCadence() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getCadence() {
        return cadence_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public Builder setCadence(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        cadence_ = value;

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public Builder setCadence(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        cadence_ = builderForValue.build();

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public Builder mergeCadence(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            cadence_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          cadence_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(cadence_).mergeFrom(value).buildPartial();
        } else {
          cadence_ = value;
        }

        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData cadence = 3;</code>
       */
      public Builder clearCadence() {
        cadence_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData power = 4;
      private com.google.android.lib.mytracks.content.Sensor.SensorData power_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public boolean hasPower() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getPower() {
        return power_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public Builder setPower(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        power_ = value;

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public Builder setPower(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        power_ = builderForValue.build();

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public Builder mergePower(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            power_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          power_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(power_).mergeFrom(value).buildPartial();
        } else {
          power_ = value;
        }

        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData power = 4;</code>
       */
      public Builder clearPower() {
        power_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;
      private com.google.android.lib.mytracks.content.Sensor.SensorData batteryLevel_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public boolean hasBatteryLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getBatteryLevel() {
        return batteryLevel_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public Builder setBatteryLevel(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        batteryLevel_ = value;

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public Builder setBatteryLevel(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        batteryLevel_ = builderForValue.build();

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public Builder mergeBatteryLevel(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000010) == 0x00000010) &&
            batteryLevel_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          batteryLevel_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(batteryLevel_).mergeFrom(value).buildPartial();
        } else {
          batteryLevel_ = value;
        }

        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData battery_level = 5;</code>
       */
      public Builder clearBatteryLevel() {
        batteryLevel_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData attention = 6;
      private com.google.android.lib.mytracks.content.Sensor.SensorData attention_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public boolean hasAttention() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getAttention() {
        return attention_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public Builder setAttention(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        attention_ = value;

        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public Builder setAttention(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        attention_ = builderForValue.build();

        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public Builder mergeAttention(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000020) == 0x00000020) &&
            attention_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          attention_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(attention_).mergeFrom(value).buildPartial();
        } else {
          attention_ = value;
        }

        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData attention = 6;</code>
       */
      public Builder clearAttention() {
        attention_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;
      private com.google.android.lib.mytracks.content.Sensor.SensorData meditation_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public boolean hasMeditation() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getMeditation() {
        return meditation_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public Builder setMeditation(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        meditation_ = value;

        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public Builder setMeditation(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        meditation_ = builderForValue.build();

        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public Builder mergeMeditation(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000040) == 0x00000040) &&
            meditation_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          meditation_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(meditation_).mergeFrom(value).buildPartial();
        } else {
          meditation_ = value;
        }

        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData meditation = 7;</code>
       */
      public Builder clearMeditation() {
        meditation_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;
      private com.google.android.lib.mytracks.content.Sensor.SensorData bpm_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public boolean hasBpm() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getBpm() {
        return bpm_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public Builder setBpm(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bpm_ = value;

        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public Builder setBpm(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        bpm_ = builderForValue.build();

        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public Builder mergeBpm(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000080) == 0x00000080) &&
            bpm_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          bpm_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(bpm_).mergeFrom(value).buildPartial();
        } else {
          bpm_ = value;
        }

        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData bpm = 8;</code>
       */
      public Builder clearBpm() {
        bpm_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;
      private com.google.android.lib.mytracks.content.Sensor.SensorData rmssd_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public boolean hasRmssd() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getRmssd() {
        return rmssd_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public Builder setRmssd(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        rmssd_ = value;

        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public Builder setRmssd(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        rmssd_ = builderForValue.build();

        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public Builder mergeRmssd(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000100) == 0x00000100) &&
            rmssd_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          rmssd_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(rmssd_).mergeFrom(value).buildPartial();
        } else {
          rmssd_ = value;
        }

        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData rmssd = 9;</code>
       */
      public Builder clearRmssd() {
        rmssd_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;
      private com.google.android.lib.mytracks.content.Sensor.SensorData heartRateRc1_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public boolean hasHeartRateRc1() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc1() {
        return heartRateRc1_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public Builder setHeartRateRc1(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartRateRc1_ = value;

        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public Builder setHeartRateRc1(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        heartRateRc1_ = builderForValue.build();

        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public Builder mergeHeartRateRc1(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000200) == 0x00000200) &&
            heartRateRc1_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          heartRateRc1_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(heartRateRc1_).mergeFrom(value).buildPartial();
        } else {
          heartRateRc1_ = value;
        }

        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc1 = 10;</code>
       */
      public Builder clearHeartRateRc1() {
        heartRateRc1_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      // optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;
      private com.google.android.lib.mytracks.content.Sensor.SensorData heartRateRc2_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public boolean hasHeartRateRc2() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public com.google.android.lib.mytracks.content.Sensor.SensorData getHeartRateRc2() {
        return heartRateRc2_;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public Builder setHeartRateRc2(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        heartRateRc2_ = value;

        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public Builder setHeartRateRc2(
          com.google.android.lib.mytracks.content.Sensor.SensorData.Builder builderForValue) {
        heartRateRc2_ = builderForValue.build();

        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public Builder mergeHeartRateRc2(com.google.android.lib.mytracks.content.Sensor.SensorData value) {
        if (((bitField0_ & 0x00000400) == 0x00000400) &&
            heartRateRc2_ != com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance()) {
          heartRateRc2_ =
            com.google.android.lib.mytracks.content.Sensor.SensorData.newBuilder(heartRateRc2_).mergeFrom(value).buildPartial();
        } else {
          heartRateRc2_ = value;
        }

        bitField0_ |= 0x00000400;
        return this;
      }
      /**
       * <code>optional .com.google.android.lib.mytracks.content.SensorData heart_rate_rc2 = 11;</code>
       */
      public Builder clearHeartRateRc2() {
        heartRateRc2_ = com.google.android.lib.mytracks.content.Sensor.SensorData.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.android.lib.mytracks.content.SensorDataSet)
    }

    static {
      defaultInstance = new SensorDataSet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.android.lib.mytracks.content.SensorDataSet)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
